---
- name: Install kernel packages and replace uname
  hosts: all
  tasks:
    - name: Install kernel packages
      ansible.builtin.package:
        name:
          - kernel
          - kernel-devel
        state: present
    - name: Replace uname to fix detection of kernel and architecture in docker
      ansible.builtin.copy:
        src: files/uname
        dest: /bin/uname
        owner: root
        group: root
        mode: "0755"
