---
- name: Add iommu to kernel command line (Intel)
  ansible.builtin.include_role:
    name: stackhpc.linux.grubcmdline
  vars:
    kernel_cmdline: # noqa: var-naming[no-role-prefix]
      - intel_iommu=on
    kernel_cmdline_remove: # noqa: var-naming[no-role-prefix]
      - ^intel_iommu=
  when: ansible_facts.processor | select('search','Intel')

- name: Set iommu=pt
  ansible.builtin.include_role:
    name: stackhpc.linux.grubcmdline
  vars:
    kernel_cmdline: # noqa: var-naming[no-role-prefix]
      - iommu=pt
    kernel_cmdline_remove: # noqa: var-naming[no-role-prefix]
      - ^iommu=
  when: iommu_pt
